### ISSUE TITLE
Docker build fails on Mac M1 machines

### ISSUE THREAD

**Issue by nazrul-kabir** [Azure-Samples/openai-chat-app-quickstart#84]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [x ] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
> You're on MAC machine(silicon based) & tried to run `docker compose up --build`

### Any log messages given by the failure
> 13.87   Building wheel for cffi (pyproject.toml): started
14.03   Building wheel for cffi (pyproject.toml): finished with status 'error'
14.04   error: subprocess-exited-with-error
14.04   
14.04   × Building wheel for cffi (pyproject.toml) did not run successfully.
14.04   │ exit code: 1
14.04   ╰─> [48 lines of output]
14.04       
14.04           No working compiler found, or bogus compiler options passed to
14.04           the compiler from Python's standard "distutils" module.  See
14.04           the error messages above.  Likely, the problem is not related
14.04           to CFFI but generic to the setup.py of any Python package that
14.04           tries to compile C code.  (Hints: on OS/X 10.8, for errors about
14.04           -mno-fused-madd see http://stackoverflow.com/questions/22313407/
14.04           Otherwise, see https://wiki.python.org/moin/CompLangPython or
14.04           the IRC channel #python on irc.libera.chat.)
14.04       
14.04           Trying to continue anyway.  If you are trying to install CFFI from
14.04           a build done in a different context, you can ignore this warning.
14.04       
14.04       running bdist_wheel
14.04       running build
14.04       running build_py
14.04       creating build
14.04       creating build/lib.linux-aarch64-cpython-311
14.04       creating build/lib.linux-aarch64-cpython-311/cffi
14.04       copying src/cffi/setuptools_ext.py -> build/lib.linux-aarch64-cpython-311/cffi
14.04       copying src/cffi/_shimmed_dist_utils.py -> build/lib.linux-aarch64-cpython-311/cffi
14.04       copying src/cffi/recompiler.py -> build/lib.linux-aarch64-cpython-311/cffi
14.04       copying src/cffi/lock.py -> build/lib.linux-aarch64-cpython-311/cffi
14.04       copying src/cffi/ffiplatform.py -> build/lib.linux-aarch64-cpython-311/cffi
14.04       copying src/cffi/__init__.py -> build/lib.linux-aarch64-cpython-311/cffi
14.04       copying src/cffi/pkgconfig.py -> build/lib.linux-aarch64-cpython-311/cffi
14.04       copying src/cffi/model.py -> build/lib.linux-aarch64-cpython-311/cffi
14.04       copying src/cffi/error.py -> build/lib.linux-aarch64-cpython-311/cffi
14.04       copying src/cffi/api.py -> build/lib.linux-aarch64-cpython-311/cffi
14.04       copying src/cffi/vengine_cpy.py -> build/lib.linux-aarch64-cpython-311/cffi
14.04       copying src/cffi/verifier.py -> build/lib.linux-aarch64-cpython-311/cffi
14.04       copying src/cffi/backend_ctypes.py -> build/lib.linux-aarch64-cpython-311/cffi
14.04       copying src/cffi/vengine_gen.py -> build/lib.linux-aarch64-cpython-311/cffi
14.04       copying src/cffi/cparser.py -> build/lib.linux-aarch64-cpython-311/cffi
14.04       copying src/cffi/_imp_emulation.py -> build/lib.linux-aarch64-cpython-311/cffi
14.04       copying src/cffi/cffi_opcode.py -> build/lib.linux-aarch64-cpython-311/cffi
14.04       copying src/cffi/commontypes.py -> build/lib.linux-aarch64-cpython-311/cffi
14.04       copying src/cffi/_cffi_include.h -> build/lib.linux-aarch64-cpython-311/cffi
14.04       copying src/cffi/parse_c_type.h -> build/lib.linux-aarch64-cpython-311/cffi
14.04       copying src/cffi/_embedding.h -> build/lib.linux-aarch64-cpython-311/cffi
14.04       copying src/cffi/_cffi_errors.h -> build/lib.linux-aarch64-cpython-311/cffi
14.04       running build_ext
14.04       building '_cffi_backend' extension
14.04       creating build/temp.linux-aarch64-cpython-311
14.04       creating build/temp.linux-aarch64-cpython-311/src
14.04       creating build/temp.linux-aarch64-cpython-311/src/c
14.04       gcc -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -fPIC -DFFI_BUILDING=1 -I/usr/include/ffi -I/usr/include/libffi -I/usr/local/include/python3.11 -c src/c/_cffi_backend.c -o build/temp.linux-aarch64-cpython-311/src/c/_cffi_backend.o
14.04       error: command 'gcc' failed: No such file or directory
14.04       [end of output]
14.04   
14.04   note: This error originates from a subprocess, and is likely not a problem with pip.
14.04   ERROR: Failed building wheel for cffi
14.04   Building wheel for pyyaml (pyproject.toml): started
14.21   Building wheel for pyyaml (pyproject.toml): finished with status 'done'
14.21   Created wheel for pyyaml: filename=PyYAML-6.0.1-cp311-cp311-linux_aarch64.whl size=45364 sha256=4676aaa1a52ab8f8b3d2ad36f77b8fe9788638a7b388525c64d876ce3210eb9b
14.21   Stored in directory: /root/.cache/pip/wheels/20/40/04/9edd5f1052f28aff139c0b315b3d5ad7ba893c93ccde03f1b4
14.22 Successfully built pyyaml
14.22 Failed to build cffi
14.22 ERROR: Could not build wheels for cffi, which is required to install pyproject.toml-based projects
------
failed to solve: process "/bin/sh -c pip3 install -r requirements.txt" did not complete successfully: exit code: 1

### Expected/desired behavior
> Build & Run the app successfully

### OS and Version?
> macOS (Ventura 13.2.1 )

### Versions
>

### Mention any other details that might be useful

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by pamelafox** [comment]
Are you inside the Dev Container or outside the Dev Container when you run that?

**Comment by nazrul-kabir** [comment]
Hi @pamelafox, outside.

**Comment by pamelafox** [comment]
Aha, that is due to move to Alpine introduced by @naioja in #74

I am adding the necessary packages in #86
